name: Publish Docker Image

on:
  push:
    branches:
      - master # Cambia 'main' si utilizas otra rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Loguearte en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Construir la imagen Docker del Backend
      - name: Build Service Docker image
        run: |
          docker build -t melitonio/stats:latest ./src/MAIT.DocumentSeriesService

      # Paso 6: Subir la imagen del Backend a Docker Hub
      - name: Push Service Docker image
        run: |
          docker push melitonio/stats:latest
